"""
GET /api/graph/communities — Community detection results with LLM summaries.

Communities are computed offline by scripts/run_gds_analytics.py (Louvain).
Each community has a summary generated by the community_rag service.
"""
from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, Depends, Query

from ...auth.deps import get_current_user
from ...core.database import get_driver
from ...db.models import User

log = logging.getLogger(__name__)
router = APIRouter(prefix="/api/graph", tags=["graph"])


@router.get("/communities")
async def list_communities(
    limit: int = Query(default=50, ge=1, le=200),
    min_size: int = Query(default=3, ge=1, description="Minimum nodes per community"),
    _: User = Depends(get_current_user),
) -> dict[str, Any]:
    """
    Return community detection results from Neo4j.

    Each community entry contains:
    - community_id    — Louvain community integer
    - size            — number of Section nodes in this community
    - sample_titles   — up to 3 representative section titles
    - summary         — LLM-generated summary (if available)
    - pagerank_avg    — average PageRank of member nodes
    - top_docs        — up to 3 most common source documents
    """
    driver = get_driver()
    with driver.session() as s:
        result = s.run(
            """
            MATCH (sec:Section)
            WHERE sec.community_id IS NOT NULL
            WITH sec.community_id AS cid,
                 collect(sec.title)[..3] AS titles,
                 collect(sec.doc_id)     AS docs,
                 count(sec)              AS size,
                 avg(coalesce(sec.pagerank, 0)) AS avg_pr,
                 collect(sec.community_summary)[0] AS summary
            WHERE size >= $min_size
            RETURN cid, titles, docs, size, avg_pr, summary
            ORDER BY size DESC
            LIMIT $limit
            """,
            min_size=min_size,
            limit=limit,
        )
        rows = [dict(r) for r in result]

    communities = []
    for row in rows:
        docs_flat: list[str] = row.get("docs") or []
        doc_counts: dict[str, int] = {}
        for d in docs_flat:
            doc_counts[d] = doc_counts.get(d, 0) + 1
        top_docs = sorted(doc_counts, key=lambda x: -doc_counts[x])[:3]

        communities.append({
            "community_id":  row["cid"],
            "size":          row["size"],
            "sample_titles": row.get("titles") or [],
            "summary":       row.get("summary") or "",
            "pagerank_avg":  round(row.get("avg_pr") or 0, 4),
            "top_docs":      top_docs,
        })

    return {
        "total":       len(communities),
        "communities": communities,
    }


@router.get("/communities/{community_id}")
async def get_community(
    community_id: int,
    _: User = Depends(get_current_user),
) -> dict[str, Any]:
    """Return all sections belonging to a specific community."""
    driver = get_driver()
    with driver.session() as s:
        result = s.run(
            """
            MATCH (sec:Section {community_id: $cid})
            RETURN sec.chunk_id AS chunk_id, sec.title AS title,
                   sec.doc_id AS doc_id, sec.pagerank AS pagerank
            ORDER BY coalesce(sec.pagerank, 0) DESC
            LIMIT 100
            """,
            cid=community_id,
        )
        sections = [dict(r) for r in result]

    return {
        "community_id": community_id,
        "count":        len(sections),
        "sections":     sections,
    }
