#!/usr/bin/env python3
"""
export_knowledge_graph.py — Neo4j 知识图谱导出工具

支持格式：
  --format json    每行一个 JSON 对象（JSONL），适合增量分析
  --format csv     节点/关系分别写 nodes.csv / edges.csv
  --format cypher  可直接在空库执行的 CREATE 语句

用法::

    cd backend
    python scripts/export_knowledge_graph.py \\
        --uri bolt://localhost:7687 \\
        --user neo4j --password secret \\
        --doc-id CPS1220 \\
        --format json \\
        --out /tmp/export/

    # 导出全量
    python scripts/export_knowledge_graph.py --format csv --out /tmp/export/

    # 仅导出某文档
    python scripts/export_knowledge_graph.py --doc-id CPS1220 --format cypher

输出文件（json/csv 模式）::

    <out>/nodes.jsonl   或  <out>/nodes.csv
    <out>/edges.jsonl   或  <out>/edges.csv
    <out>/export_meta.json      （导出元信息：时间、数量、参数）
"""
from __future__ import annotations

import argparse
import csv
import json
import logging
import os
import sys
from datetime import datetime
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger(__name__)

# ── Neo4j queries ─────────────────────────────────────────────────────────────

_NODES_CYPHER = """
MATCH (n)
WHERE $doc_id = '' OR n.doc_id = $doc_id
RETURN
  id(n)            AS _neo4j_id,
  labels(n)        AS _labels,
  properties(n)    AS _props
ORDER BY id(n)
"""

_EDGES_CYPHER = """
MATCH (a)-[r]->(b)
WHERE $doc_id = '' OR (a.doc_id = $doc_id OR b.doc_id = $doc_id)
RETURN
  id(a)            AS _src_id,
  id(b)            AS _dst_id,
  type(r)          AS _type,
  properties(r)    AS _props
ORDER BY id(r)
"""


# ── Serialisation helpers ──────────────────────────────────────────────────────

def _flatten(props: dict) -> dict:
    """Ensure all values are JSON-serialisable."""
    out = {}
    for k, v in (props or {}).items():
        if isinstance(v, (str, int, float, bool, type(None))):
            out[k] = v
        elif isinstance(v, list):
            out[k] = [str(i) for i in v]
        else:
            out[k] = str(v)
    return out


def _row_to_node(row) -> dict:
    props = _flatten(dict(row["_props"]))
    props["_neo4j_id"] = row["_neo4j_id"]
    props["_labels"] = list(row["_labels"])
    return props


def _row_to_edge(row) -> dict:
    props = _flatten(dict(row["_props"]))
    props["_src_id"] = row["_src_id"]
    props["_dst_id"] = row["_dst_id"]
    props["_type"] = row["_type"]
    return props


# ── Writers ───────────────────────────────────────────────────────────────────

def _write_jsonl(items: list[dict], path: Path) -> None:
    path.write_text(
        "\n".join(json.dumps(item, ensure_ascii=False) for item in items) + "\n",
        encoding="utf-8",
    )


def _write_csv(items: list[dict], path: Path) -> None:
    if not items:
        path.write_text("", encoding="utf-8")
        return
    keys = list(dict.fromkeys(k for item in items for k in item))
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
        w.writeheader()
        w.writerows(items)


def _write_cypher(nodes: list[dict], edges: list[dict], path: Path) -> None:
    lines: list[str] = ["// Auto-generated by export_knowledge_graph.py", ""]
    for node in nodes:
        nid = node["_neo4j_id"]
        labels = ":".join(node.get("_labels", ["Node"]))
        props = {k: v for k, v in node.items() if not k.startswith("_")}
        prop_str = ", ".join(f"{k}: {json.dumps(v, ensure_ascii=False)}" for k, v in props.items())
        lines.append(f"CREATE (n{nid}:{labels} {{{prop_str}}});")
    lines.append("")
    for edge in edges:
        src, dst, rel = edge["_src_id"], edge["_dst_id"], edge["_type"]
        props = {k: v for k, v in edge.items() if not k.startswith("_")}
        prop_str = (", ".join(f"{k}: {json.dumps(v, ensure_ascii=False)}" for k, v in props.items()))
        prop_clause = f" {{{prop_str}}}" if prop_str else ""
        lines.append(f"MATCH (a) WHERE id(a) = {src} MATCH (b) WHERE id(b) = {dst} CREATE (a)-[:{rel}{prop_clause}]->(b);")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Export Neo4j knowledge graph")
    parser.add_argument("--uri",      default=os.getenv("NEO4J_URI",      "bolt://localhost:7687"))
    parser.add_argument("--user",     default=os.getenv("NEO4J_USER",     "neo4j"))
    parser.add_argument("--password", default=os.getenv("NEO4J_PASSWORD",  "neo4j"))
    parser.add_argument("--doc-id",   default="", help="Filter to single document (empty = all)")
    parser.add_argument("--format",   choices=["json", "csv", "cypher"], default="json")
    parser.add_argument("--out",      default=".", help="Output directory")
    args = parser.parse_args()

    try:
        from neo4j import GraphDatabase
    except ImportError:
        log.error("neo4j Python driver not installed: pip install neo4j")
        sys.exit(1)

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    log.info("Connecting to %s …", args.uri)
    driver = GraphDatabase.driver(args.uri, auth=(args.user, args.password))

    with driver.session() as session:
        log.info("Fetching nodes (doc_id=%r) …", args.doc_id or "ALL")
        node_rows = list(session.run(_NODES_CYPHER, doc_id=args.doc_id))
        nodes = [_row_to_node(r) for r in node_rows]

        log.info("Fetching edges …")
        edge_rows = list(session.run(_EDGES_CYPHER, doc_id=args.doc_id))
        edges = [_row_to_edge(r) for r in edge_rows]

    driver.close()
    log.info("Fetched %d nodes, %d edges", len(nodes), len(edges))

    if args.format == "json":
        _write_jsonl(nodes, out_dir / "nodes.jsonl")
        _write_jsonl(edges, out_dir / "edges.jsonl")
        log.info("Wrote nodes.jsonl + edges.jsonl")
    elif args.format == "csv":
        _write_csv(nodes, out_dir / "nodes.csv")
        _write_csv(edges, out_dir / "edges.csv")
        log.info("Wrote nodes.csv + edges.csv")
    else:
        cypher_path = out_dir / "graph.cypher"
        _write_cypher(nodes, edges, cypher_path)
        log.info("Wrote %s", cypher_path)

    meta = {
        "exported_at": datetime.now().isoformat(),
        "uri": args.uri,
        "doc_id": args.doc_id or "ALL",
        "format": args.format,
        "node_count": len(nodes),
        "edge_count": len(edges),
    }
    (out_dir / "export_meta.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    log.info("Done. export_meta.json written to %s", out_dir)


if __name__ == "__main__":
    main()
